#version 460

layout(local_size_x = 16, local_size_y = 16) in;


layout(binding = 0) uniform sampler3D CloudNoise;
layout(binding = 1) uniform sampler3D CloudDetail;

layout(rgba16f, binding = 0) uniform image2D outputImage;


layout(std140, binding = 0) uniform CameraData
{
    mat4 View; 
    mat4 Projection;
    mat4 InverseViewProjection;
    vec3 Position;
    float pad1;
};

layout(std140, binding = 1) uniform FrameData
{
    vec2 res;
    float time;
    float pad;

};

layout(std140, binding = 2) uniform CloudData
{
   vec3 CloudColor;
   float NoiseBaseScale;

   vec3 ShapeOffset;
   float ShapeOffsetSpeed;

   vec3 DetailOffset;
   float DetailOffsetSpeed;

   vec3 boxMin;
   float DetailNoiseScale;

   vec3 boxMax;
   float SunIntensity;

   vec3 SunDir;
   float pad13;

   vec3 SunColor;
   float pad14;
};

const float PI = 3.14159;


const int MAX_STEPS = 100;
const float ABSORPTION = 8.0;
const vec3 SKY_COLOR = vec3(0.1,0.1,0.6);

const int LIGHT_STEPS = 6;
const float LIGHT_STEP_SIZE = 0.4;
const float LIGHT_ABSORPTION = 2.0;



float remap(float value, float oldMin, float oldMax, float newMin, float newMax)
{
    return newMin + (value - oldMin) / (oldMax - oldMin) * (newMax - newMin);
}

float SampleDensity(vec3 RayPos)
{
    vec3 size = boxMax - boxMin;
    vec3 uvw = (RayPos - boxMin) * 0.01 * NoiseBaseScale;
    vec3 shapeSamplePos = uvw + (vec3(ShapeOffset.x + time, ShapeOffset.y, ShapeOffset.z)) * ShapeOffsetSpeed;


    vec4 baseNoise = texture(CloudNoise, shapeSamplePos);

    float lowFreqFBM = dot(baseNoise.gba, vec3(0.625, 0.25, 0.125));
    float baseShape = baseNoise.r;//remap(baseNoise.r, lowFreqFBM - 1.0, 1.0, 0.0, 1.0);

    if (baseShape <= 0.0) return 0.0;

    vec3 detailNoise = texture(CloudDetail, uvw * 0.1).rgb;
    float highFreqFBM = dot(detailNoise, vec3(0.625, 0.25, 0.125));

    float highFreqModifier = mix(highFreqFBM, 1.0 - highFreqFBM, clamp(baseShape * 5.0, 0.0, 1.0));

    float finalDensity = remap(baseShape, highFreqModifier * 0.2, 1.0, 0.0, 1.0);
    return clamp(finalDensity, 0.0, 1.0);
}

float PhaseFun(float cosAngle, float g)
{
    float g2 = g * g;
    return (1.0 - g2) / (4.0 * PI * pow(1.0 + g2 - 2.0 * g * cosAngle, 1.5));
}

float LightMarch(vec3 RayPos)
{
    float totalDensity = 0.0;
    vec3 lightStep = SunDir * LIGHT_STEP_SIZE;
    vec3 samplePos = RayPos;

    for(int i = 0; i < LIGHT_STEPS; ++i)
    {
        samplePos += lightStep;

        if(any(lessThan(samplePos, boxMin)) || any(greaterThan(samplePos,boxMax)))
            break;

        totalDensity += SampleDensity(samplePos);
    }

    return exp(-totalDensity * LIGHT_ABSORPTION * LIGHT_STEP_SIZE);
}

bool intersectBox(vec3 rayOrigin, vec3 rayDir, vec3 boxMin, vec3 boxMax, out vec2 StartEnd)
{
    vec3 invDir = 1.0 / rayDir;

    vec3 t0 = (boxMin - rayOrigin) * invDir;
    vec3 t1 = (boxMax - rayOrigin) * invDir;

    vec3 tMin = min(t0, t1);
    vec3 tMax = max(t0, t1);

    float nearT = max(max(tMin.x, tMin.y), tMin.z);
    float farT  = min(min(tMax.x, tMax.y), tMax.z);

    StartEnd = vec2( max(nearT,0.0) , farT);

    return farT >= max(nearT, 0.0);
}

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size  = imageSize(outputImage);

    if (pixel.x >= size.x || pixel.y >= size.y)
        return;

    vec2 uv = (vec2(pixel) + 0.5) / vec2(size);
    vec2 ndc = uv * 2.0 - 1.0;

    // Near/far points in clip space
    vec4 nearPoint = InverseViewProjection *
                     vec4(ndc, -1.0, 1.0);

    vec4 farPoint = InverseViewProjection *
                    vec4(ndc, 1.0, 1.0);

    nearPoint /= nearPoint.w;
    farPoint  /= farPoint.w;

    vec3 rayOrigin = Position;
    vec3 rayDir = normalize(farPoint.xyz - rayOrigin);

    vec3 FinalColor = vec3(0.0);
    vec2 StartEnd;
    if (intersectBox(rayOrigin, rayDir, boxMin, boxMax, StartEnd))
    {
        float Start = StartEnd.x;
        float End = StartEnd.y;
        float t = Start;
        float stepSize = (End - Start) / float(MAX_STEPS);

        
        float Transmitance = 1.0;
        vec3 Color = vec3(0.0);

        float cosAngle = dot(rayDir, SunDir);
        float phase = PhaseFun(cosAngle, 0.3);

        for(int s = 0; s < MAX_STEPS; ++s)
        {
            if(t > End || Transmitance <= 0.01)
                break;

            vec3 CurrentPos = rayOrigin + rayDir * t;


            float density = SampleDensity(CurrentPos);
            
            if(density > 0.0)
            {
                float lightTransmitance = LightMarch(CurrentPos);
                vec3 litColor = SunColor * SunIntensity * lightTransmitance * phase + vec3(0.2);
                    

                float stepAbsorption = exp(-density * ABSORPTION * stepSize);

                Color += CloudColor * litColor * Transmitance * (1 - stepAbsorption);

                Transmitance *= stepAbsorption;

            }

            t += stepSize;
        }

        FinalColor = Color + SKY_COLOR * Transmitance;
    }
    else
    {
        float sunDot = dot(rayDir, normalize(SunDir));
        float sunDisc = smoothstep(0.9995, 0.9999, sunDot); 
        vec3 sunColor = SunColor * 20.0;

        FinalColor = mix(SKY_COLOR, sunColor, sunDisc);    
    }
    imageStore(outputImage, pixel, vec4(FinalColor.x, FinalColor.y, FinalColor.z, 1.0));
}
