#version 460

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(rgba8, binding = 0) uniform image3D outputMainImage;
layout(rgba8, binding = 1) uniform image3D outputDetailImage;


struct NoiseChannelParams
{
    float cells;
    int octaves;
    float seed;
    float _pad;
};

layout( std140, binding = 1) uniform NoiseData
{
    NoiseChannelParams channels[7];
};


const float PI = 3.1416;

float hash13(vec3 p)
{
    p = fract(p * 0.1031);
    p += dot(p, p.yzx + 33.33);
    return fract((p.x + p.y) * p.z);
}

vec3 randomPoint(vec3 cell, float period, float seed)
{
    cell = mod(cell, period);
    cell = mod(cell + period, period);

    return vec3(
        hash13(cell + seed * 13.17),
        hash13(cell + seed * 27.31),
        hash13(cell + seed * 41.73)
    );
}

float WorleyNoise(vec3 size, float cells, float seed)
{
    ivec3 pixel = ivec3(gl_GlobalInvocationID);

    vec3 uv = (vec3(pixel) + 0.5) / vec3(size);

    vec3 gridPos = uv * cells;
    vec3 cell = floor(gridPos);
    vec3 localPos = fract(gridPos);

    float minDistance = 1e10;

    for(int y = -1; y <= 1; ++y)
    {
        for(int x = -1; x <= 1; ++x)
        {
            for(int z = -1; z <= 1; ++z)
            {
                vec3 neighbour = vec3(x,y,z);

                vec3 featurePoint = randomPoint(cell + neighbour, cells, seed);

                vec3 delta = neighbour + featurePoint - localPos;

                float distance = dot(delta,delta);

                minDistance = min(minDistance,distance);
            }
        }
    }

    return sqrt(minDistance);
}

vec3 fade(vec3 x)
{
    return x * x * x * (x * (x * 6.0 - 15.0) + 10.0);
}

vec3 grad(vec3 cell, float period, float seed)
{
    cell = mod(cell, period);
    cell = mod(cell + period, period);

    float h1 = hash13(cell + seed * 4321.652);
    float h2 = hash13(cell + seed * 5342.154);

    float theta = h1 * 2.0 * PI;

    // Calculate the sin(phi) uniformly instead of 
    // generating the phi to ensure that angles stay uniform
    // and aren't biased to poles.

    float sin_phi = h2 * 2.0 - 1.0; // [-1:1)
    float cos_phi = sqrt(1 - sin_phi * sin_phi);

    return vec3(
            cos_phi * cos(theta),
            cos_phi * sin(theta),
            sin_phi
    );
}

// [-1:1)
float Perlin(vec3 size, float cells, float seed)
{
    ivec3 pixel = ivec3(gl_GlobalInvocationID);

    vec3 uv = (vec3(pixel) + 0.5) / vec3(size);
    vec3 gridPos = uv * cells;

    vec3 cell = floor(gridPos);

    vec3 f = fract(gridPos);
    vec3 u = fade(f);

    // Get values for each grid vertex
    float v000 = dot( grad(cell + vec3(0,0,0), cells, seed), f - vec3(0,0,0));
    float v100 = dot( grad(cell + vec3(1,0,0), cells, seed), f - vec3(1,0,0));
    float v010 = dot( grad(cell + vec3(0,1,0), cells, seed), f - vec3(0,1,0));
    float v110 = dot( grad(cell + vec3(1,1,0), cells, seed), f - vec3(1,1,0));
    float v001 = dot( grad(cell + vec3(0,0,1), cells, seed), f - vec3(0,0,1));
    float v101 = dot( grad(cell + vec3(1,0,1), cells, seed), f - vec3(1,0,1));
    float v011 = dot( grad(cell + vec3(0,1,1), cells, seed), f - vec3(0,1,1));
    float v111 = dot( grad(cell + vec3(1,1,1), cells, seed), f - vec3(1,1,1));

    // Interpolate

    // x
    float vx00 = mix(v000, v100, u.x);
    float vx01 = mix(v001, v101, u.x);
    float vx10 = mix(v010, v110, u.x);
    float vx11 = mix(v011, v111, u.x);

    // y
    float vxy0 = mix(vx00, vx10, u.y);
    float vxy1 = mix(vx01, vx11, u.y);

    // z
    float vxyz = mix(vxy0, vxy1, u.z);

    return vxyz;
}

float PerlinFBM(vec3 size, float baseCells, int octaves, float seed)
{
    float sum = 0.0;
    float amplitude = 0.5;
    float totalAmplitude = 0.0;
    float cells = baseCells;

    for (int i = 0; i < octaves; ++i)
    {
        sum += Perlin(size,cells, seed + float(i)) * amplitude;
        totalAmplitude += amplitude;
        amplitude *= 0.5;
        cells *= 2.0;
    }
    return (sum / totalAmplitude + 1.0) / 2.0 ; // ~[0,1]
}

float WorleyFBM(vec3 size, float baseCells, int octaves, float seed)
{
    float sum = 0.0;
    float amplitude = 0.5;
    float totalAmplitude = 0.0;
    float cells = baseCells;

    for (int i = 0; i < octaves; ++i)
    {
        float w = clamp(WorleyNoise(size,cells, seed + float(i)),0.0,1.0);
        sum += w * amplitude;
        totalAmplitude += amplitude;
        amplitude *= 0.5;
        cells *= 2.0;
    }
    return sum / totalAmplitude; // ~[0, ~1]
}

float remap(float value, float oldMin, float oldMax, float newMin, float newMax)
{
    return newMin + (value - oldMin) / (oldMax - oldMin) * (newMax - newMin);
}

float PerlinWorley(vec3 size, float cells, int octaves, float seed)
{
    float perlin = PerlinFBM(size,cells, octaves, seed);
    float worley = WorleyFBM(size, cells * 2.0, octaves, seed);        // Worley usually at higher base frequency

    // Worley acts as an erosion floor: below it, Perlin gets clamped to 0.
    //return remap(perlin,worley, 1.0, 0.0, 1.0);
    return clamp(perlin - worley,0.0,1.0);
}

void main()
{
    ivec3 voxel = ivec3(gl_GlobalInvocationID);

    ivec3 SizeMain = imageSize(outputMainImage);

    if(voxel.x >= SizeMain.x || voxel.y >= SizeMain.y || voxel.z >= SizeMain.z)
        return;

    NoiseChannelParams mainR   = channels[0];
    NoiseChannelParams mainG   = channels[1];
    NoiseChannelParams mainB   = channels[2];
    NoiseChannelParams mainA   = channels[3];
    
    NoiseChannelParams detailR = channels[4];
    NoiseChannelParams detailG = channels[5];
    NoiseChannelParams detailB = channels[6];

    vec4 MainResult;
    MainResult.r = 1.0 - WorleyFBM(SizeMain, mainR.cells, mainR.octaves, mainR.seed);
    MainResult.g = WorleyFBM(SizeMain, mainG.cells, mainG.octaves, mainG.seed) ;
    MainResult.b = WorleyFBM(SizeMain, mainB.cells, mainB.octaves, mainB.seed) ;
    MainResult.a = WorleyFBM(SizeMain, mainA.cells, mainA.octaves, mainA.seed) ;
    imageStore(outputMainImage,voxel, MainResult);

    ivec3 SizeDetail = imageSize(outputDetailImage);
    
    if(voxel.x >= SizeDetail.x || voxel.y >= SizeDetail.y || voxel.z >= SizeDetail.z)
        return;

    vec4 DetailResult;
    DetailResult.r = PerlinFBM(SizeDetail, detailR.cells, detailR.octaves, detailR.seed);
    DetailResult.g = PerlinFBM(SizeDetail, detailG.cells, detailG.octaves, detailG.seed);
    DetailResult.b = PerlinFBM(SizeDetail, detailB.cells, detailB.octaves, detailB.seed);
    DetailResult.a = 0.0;

    imageStore(outputDetailImage, voxel, DetailResult);

}
