#version 460

layout(local_size_x = 8, local_size_y = 8) in;

layout(rgba16f, binding = 0) uniform image2D outputImage;

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);

    ivec2 size = imageSize(outputImage);

    if (pixel.x >= size.x || pixel.y >= size.y)
        return;

    vec2 uv = vec2(pixel) / vec2(size);

    imageStore(outputImage, pixel, vec4(uv.x, uv.y, 0.0, 1.0));
}
