#include "TextureHelper.hpp"

#include <glad/gl.h>
#include <iostream>


// Note this code was generated by AI, i didn't bother to check correctness

namespace Renderer
{

namespace Helper
{

unsigned int ToGL(InternalFormat format)
{
    switch (format)
    {
        case InternalFormat::R8:
            return GL_R8;
        case InternalFormat::RG8:
            return GL_RG8;
        case InternalFormat::RGB8:
            return GL_RGB8;
        case InternalFormat::RGBA8:
            return GL_RGBA8;

        case InternalFormat::R16:
            return GL_R16;
        case InternalFormat::RG16:
            return GL_RG16;
        case InternalFormat::RGB16:
            return GL_RGB16;
        case InternalFormat::RGBA16:
            return GL_RGBA16;

        case InternalFormat::R16F:
            return GL_R16F;
        case InternalFormat::RG16F:
            return GL_RG16F;
        case InternalFormat::RGB16F:
            return GL_RGB16F;
        case InternalFormat::RGBA16F:
            return GL_RGBA16F;

        case InternalFormat::R32F:
            return GL_R32F;
        case InternalFormat::RG32F:
            return GL_RG32F;
        case InternalFormat::RGB32F:
            return GL_RGB32F;
        case InternalFormat::RGBA32F:
            return GL_RGBA32F;

        case InternalFormat::R8I:
            return GL_R8I;
        case InternalFormat::RG8I:
            return GL_RG8I;
        case InternalFormat::RGBA8I:
            return GL_RGBA8I;

        case InternalFormat::R8UI:
            return GL_R8UI;
        case InternalFormat::RG8UI:
            return GL_RG8UI;
        case InternalFormat::RGBA8UI:
            return GL_RGBA8UI;

        case InternalFormat::R16I:
            return GL_R16I;
        case InternalFormat::RG16I:
            return GL_RG16I;
        case InternalFormat::RGBA16I:
            return GL_RGBA16I;

        case InternalFormat::R16UI:
            return GL_R16UI;
        case InternalFormat::RG16UI:
            return GL_RG16UI;
        case InternalFormat::RGBA16UI:
            return GL_RGBA16UI;

        case InternalFormat::R32I:
            return GL_R32I;
        case InternalFormat::RG32I:
            return GL_RG32I;
        case InternalFormat::RGBA32I:
            return GL_RGBA32I;

        case InternalFormat::R32UI:
            return GL_R32UI;
        case InternalFormat::RG32UI:
            return GL_RG32UI;
        case InternalFormat::RGBA32UI:
            return GL_RGBA32UI;

        case InternalFormat::Depth16:
            return GL_DEPTH_COMPONENT16;
        case InternalFormat::Depth24:
            return GL_DEPTH_COMPONENT24;
        case InternalFormat::Depth32F:
            return GL_DEPTH_COMPONENT32F;

        case InternalFormat::Depth24Stencil8:
            return GL_DEPTH24_STENCIL8;
        case InternalFormat::Depth32FStencil8:
            return GL_DEPTH32F_STENCIL8;
    }
    
    std::cout << "Couldnt resolve Internal Format" << std::endl;

    return GL_NONE;
}


unsigned int ToGL(Format format)
{
    switch (format)
    {
        case Format::Red:
            return GL_RED;
        case Format::RG:
            return GL_RG;
        case Format::RGB:
            return GL_RGB;
        case Format::RGBA:
            return GL_RGBA;

        case Format::RedInteger:
            return GL_RED_INTEGER;
        case Format::RGInteger:
            return GL_RG_INTEGER;
        case Format::RGBInteger:
            return GL_RGB_INTEGER;
        case Format::RGBAInteger:
            return GL_RGBA_INTEGER;

        case Format::DepthComponent:
            return GL_DEPTH_COMPONENT;
        case Format::DepthStencil:
            return GL_DEPTH_STENCIL;
    }

    std::cout << "Couldn't resolve Format" << std::endl;

    return GL_NONE;
}


unsigned int ToGL(DataType type)
{
    switch (type)
    {
        case DataType::UnsignedByte:
            return GL_UNSIGNED_BYTE;
        case DataType::Byte:
            return GL_BYTE;

        case DataType::UnsignedShort:
            return GL_UNSIGNED_SHORT;
        case DataType::Short:
            return GL_SHORT;

        case DataType::UnsignedInt:
            return GL_UNSIGNED_INT;
        case DataType::Int:
            return GL_INT;

        case DataType::HalfFloat:
            return GL_HALF_FLOAT;
        case DataType::Float:
            return GL_FLOAT;
    }

    std::cout << "Couldn't resolve DataType" << std::endl;
    return GL_NONE;
}
unsigned int ToGL(TextureType type)
{
            switch(type)
            {
                case TextureType::Texture2D:
                    return GL_TEXTURE_2D;

                case TextureType::Texture3D:
                    return GL_TEXTURE_3D;

                case TextureType::TextureCube:
                    return GL_TEXTURE_CUBE_MAP;
            }
            std::cout<< "Couldnt resolve Texture Type macro" << std::endl;
            return 0;
}

} // namespace Helper

} // namespace Renderer
